// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lssslyffieqspjjsiszk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzc3NseWZmaWVxc3BqanNpc3prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NDgxMTgsImV4cCI6MjA3NDUyNDExOH0.ZEpLhThP9DwHvoKZNr5CT60Pog98mdS0UzGoMeXQayA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});